name:          FutureLab Engineering Best Practices
title:         FutureLab Engineering Best Practices
description:   Engineering best practices used by FutureLab.
url:           https://futurelabnz.github.io/
baseurl:       /engineering-best-practices
author:
  name:    futurelabnz
  email:   hello@futurelab.co.nz
  github:  futurelabnz
  twitter: futurelabnz

markdown:      kramdown
permalink:     pretty
highlighter:   rouge
encoding:      utf-8
kramdown:
  input: GFM
sass:
  sass_dir: _includes/_sass
